version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: '04:00'
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    commit-message:
      prefix: deps
      include: scope
    labels:
      - dependencies
      - security

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: '04:15'
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    commit-message:
      prefix: ci
      include: scope
    labels:
      - dependencies
      - ci
